### ISSUE TITLE
Testnet stalls with low block count

### ISSUE THREAD

**Issue by Scottrock** [z-classic/zclassic#101]
### Describe the issue
Testnet stalls at block 73715
test-dnsseed.rotorproject.org has a block height of 73715
when setgenerate is set to true - peers inform that the chain is still downloading at 73715

#### If so, please list the steps to reproduce below:
1. run zcashd with -testnet
2. sync peer and setgenerate to true

### Expected behaviour
Testnet peer should sync to latest block and start mining.

### Actual behaviour + errors
3. block download stalls at 73715, read error message - cannot mine, blocks syncing
4. Ping test-dnsseed.rotorproject.org - peer is listening
5. run getpeerinfo - test-dnsseed.rotorproject.org is listed (by IP)

### The version of Zcash you were using:
version v1.0.10-1-f94256cB

### Machine specs:
- OS name + version: Debian 9
- CPU: Xeon E5520
- RAM: 12GB
- Disk size: 500GB
- Disk Type (HD/SDD): HDD
- Linux kernel version (uname -a): 4.9.30-2
- Compiler version (gcc -version): 6.3.0

**Comment by aayanl** [comment]
it's because our zclassic nodes connect to zcash nodes. Solutions would be changing the magic values (requires HF) and changing the ports (partitions the network). We should do both and the testnet port should be changed next release
