### ISSUE TITLE
Can't build because of libsnark file download failure.

### ISSUE THREAD

**Issue by miningpoolhub** [z-classic/zclassic#103]
### Describe the issue
Please provide a general summary of the issue you're experiencing

Can't build.

#### If so, please list the steps to reproduce below:
1. git clone https://github.com/z-classic/zclassic
2. cd zclassic
3. git checkout tags/v1.0.10
4. ./zcutil/build.sh

### Expected behaviour
Tell us what should happen

Build successfully.

### Actual behaviour + errors
Tell us what happens instead including any noticable error output (any messages displayed on-screen when e.g. a crash occurred)

Fetching libsnark...
https://z.cash/depends-sources/libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz:
2017-09-15 12:23:19 ERROR 404: Not Found.

And stops to build

**Comment by aayanl** [comment]
Fixed

**Comment by miningpoolhub** [comment]
Thanks!

**Comment by shwuhk** [comment]
I would like to say that it happens again. Please help . Thanks.
