### ISSUE TITLE
zcashd does not synchronize

### ISSUE THREAD

**Issue by lutsifer** [z-classic/zclassic#104]
While installing zclassic on my ubuntu 16.04 I've stuck after the step with starting zcashd and waiting to start synchronizing blocks.

I have 0 connections no matter what i do about the port forwarding. 
It worth mentioning that I had no problems at all doing same thing with hush and zcash on same machine yesterday.
Of course I am clearing params folder before each coin installation.

that is my conf:
addnode=dnsseed.zclassic.org
addnode=dnsseed.rotorproject.org
rpcuser=some user here
rpcpassword=some password here

**Comment by brunohass** [comment]
@lutsifer same here.

Found this: https://www.coinexchange.io/network/peers/ZCL

But, looks like the current release try to connect on a different port than the default 8133.
So, when you copy the list from the site above you need to "force" the port, eg:

`addnode=104.207.149.241`

became

`addnode=104.207.149.241:8133`

After doing this I was able to sync.

Cheers!

**Comment by lutsifer** [comment]
@brunohass 
Cheers...
I can't believe it actually worked :pager:
