### ISSUE TITLE
Rust fails to download/install while trying to compile zclassic 1.0.10 for Windows

### ISSUE THREAD

**Issue by mascondante** [z-classic/zclassic#107]
### Describe the issue
Trying to compile doesn't download rust. Can tell because large file and it just skips right past like nothing happened.

#### If so, please list the steps to reproduce below:
1. sudo ./zcutil/build-win.sh -j$(nproc)
2. Wait for everything else to compile until it gets to rust
3. Fail complaining about unable to sha256

### Expected behaviour
Download rust.

### Actual behaviour + errors
Doesn't download rust.
`Checksum missing or mismatched for rust source. Forcing re-download.
mkdir -p /mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/sources/download-stamps /mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/sources
rm -f /mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/sources/download-stamps/.stamp_fetched-rust-.hash
touch /mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/sources/download-stamps/.stamp_fetched-rust-.hash
cd /mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/sources/download-stamps; (test -f /mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/sources/ || ( mkdir -p /mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/work/download/rust-1.16.0 && echo Fetching rust... && ( wget --timeout=10 --tries=3 -nv -O "/mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/work/download/rust-1.16.0/.temp" "https://z.cash/depends-sources/" || wget --timeout=10 --tries=3 -nv -O "/mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/work/download/rust-1.16.0/.temp" "https://static.rust-lang.org/dist/rust-1.16.0-x86_64-unknown-linux-gnu.tar.gz/" ) && echo "  /mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/work/download/rust-1.16.0/.temp" > /mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/work/download/rust-1.16.0/..hash && sha256sum -c /mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/work/download/rust-1.16.0/..hash && mv /mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/work/download/rust-1.16.0/.temp /mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/sources/ && rm -rf /mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/work/download/rust-1.16.0 ))
Fetching rust...
2017-10-04 23:17:52 URL:https://z.cash/depends-sources/ [7520] -> "/mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/work/download/rust-1.16.0/.temp" [1]
sha256sum: /mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/work/download/rust-1.16.0/..hash: no properly formatted SHA256 checksum lines found
funcs.mk:242: recipe for target '/mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/sources/download-stamps/.stamp_fetched-rust-.hash' failed
make: *** [/mnt/c/Users/Administrator/Desktop/zclassic-1.0.10/depends/sources/download-stamps/.stamp_fetched-rust-.hash] Error 1
+ ./autogen.sh
./zcutil/build-win.sh: line 44: ./autogen.sh: No such file or directory`

### The version of Zcash you were using:
1.0.10

### Machine specs:
- OS name + version: Ubuntu 16.04.3 LTS running under WSL in Windows 10
- CPU: Intel Core i3 4130
- RAM: 16GB
- Disk size: 960GB
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a): Linux JP-MAINv3 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc -version): Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

### Any extra information that might be useful in the debugging process.
I've tore through everything I know how and downloaded the package manually. I'm not sure how to place the package so it will be seen and not flag it as not yet downloaded or bad checksum.

--disable-rust does no good either. Still tries to download it anyway.

### Do you have a back up of `~/.zcash` directory and/or take a VM snapshot?
No. I'm not sure I can snapshot from WSL as it is running native beside windows instead of in VM.

**Comment by sennevb** [comment]
a precompiled windows wallet would be nice, old stopped working ;-)

**Comment by sdustmcore** [comment]
please try: 
http://pan.baidu.com/s/1nuFGKNf  passwd：4gzr
version v1.0.10-1-c71b0bb-dirty

replace the files with same name in eleos

**Comment by PFFyodor** [comment]
sdustmcore, file not found :(

**Comment by sdustmcore** [comment]
update link:  https://pan.baidu.com/s/1cK04Xo   passwd: kujc

**Comment by sdustmcore** [comment]
Zclassic Daemon version v1.0.10-1-588ec1c-dirty
https://pan.baidu.com/s/1dFi0IAl     passwd: cs2g
I have never test this version, because my eleos was deleted.

**Comment by PFFyodor** [comment]
sdustmcore, thank you, i would try, tell me, what do you use in eleos deleted? may be you have recomendations?

**Comment by sdustmcore** [comment]
I think the eleos project was dead (too slow )
and I have no zcl any more

**Comment by PFFyodor** [comment]
TY, sdustmcore, you was a very helpfull!

**Comment by 2sgl** [comment]
Could someone please upload windows build of version 1.0.10-1 on some normal file sharing service. Baidu requires registration.

**Comment by bmatthewshea** [comment]
The problem is it's trying to load the sha256sum for `./zclassic/depends/work/download/rust-1.16.0/.temp` in file `./zclassic/depends/work/download/rust-1.16.0/..hash` but the `..hash` file never has the has calculated. It simply has `  ./zclassic/depends/work/download/rust-1.16.0/.temp`. (No checksum was calculated before the two spaces.) Hence sha256sum fails because there is no checksum for that file.

**Comment by bmatthewshea** [comment]
Also, since windows build instructions are included - why can't the developers put the EXE in releases? If your source simply doesn't compile then remove it. If it does compile for you, where is a windows release build?

**Comment by sdustmcore** [comment]
new version
Zclassic Daemon version v1.0.10-1-7609f5d-dirty
https://pan.baidu.com/s/1c2ATPks

**Comment by 2sgl** [comment]
Thanks but baidu is no use for non chinese requires registration and installing a software in chinese language

**Comment by sdustmcore** [comment]
https://mega.nz/#F!A7pRVJ4D!LcK-vV_fEE4FZxmFhLahSQ

https://mega.nz/#!pqQRBCjZ!e5PfvZrFLB1CRVHhkPcJL229npO4yvUN9D7DLeUpt8E

**Comment by johandjoz** [comment]
Hi @sdustmcore , please can you provide the information needed to correct the problem ?

**Comment by sdustmcore** [comment]
Sure, I will upload my patch and cross-building method.

**Comment by sdustmcore** [comment]
Please check https://github.com/sdustmcore/zclassic.git  ,  and switch to ForWin branch
and read "cross_compiling_zcl_for_win_using_mingw32-w64.txt"

**Comment by floreslorca** [comment]
@bmatthewshea where do you have to make that change, i looked at @sdustmcore solution, and he seem to just manually install rust instead.

**Comment by nimbosa** [comment]
https://github.com/z-classic/zclassic/compare/master...sdustmcore:ForWin#diff-87cf508115ddbd568a175a33476d6311
