### ISSUE TITLE
Zclassic stopped due to version deprecation.

### ISSUE THREAD

**Issue by miningpoolhub** [z-classic/zclassic#109]
I'm running zclassic version 1001051
Zclassic stopped due to version deprecation few minutes ago.

I could only run it again with below command
disabledeprecation=1.0.10-1

Please fix this.

**Comment by chilledgamer1985** [comment]
@miningpoolhub  im having to do the same right now for my pool to :/ hopefully they update the wallet soon

**Comment by aayanl** [comment]
Fix is in master

**Comment by matthewjamesr** [comment]
Closing because fix is in master, please `git pull` and build.

**Comment by sohrab007006** [comment]
I can not connect to ledger with Electrum-Zclassic, can you help me?
