### ISSUE TITLE
what is zclassic mainnet?

### ISSUE THREAD

**Issue by madtomic** [z-classic/zclassic#11]
Follow the installation steps, ran the zclassic and i'm on zcash mainnet? How to get on zclassic main net?

**Comment by heyrhett** [comment]
Don't checkout v1.0.1 like int their instructions:

git checkout v1.0.1

You have to checkout master.  Soon, we will have update to 1.0.2 and have a tag set.

**Comment by madtomic** [comment]
I didn't use their instructions. I use what is here. one to install dependencies and next three to build and run.

Get dependencies:
sudo apt-get install \
      build-essential pkg-config libc6-dev m4 g++-multilib \
      autoconf libtool ncurses-dev unzip git python \
      zlib1g-dev wget bsdmainutils automake
Install
# Build
./zcutil/build.sh -j$(nproc)
# fetch key
./zcutil/fetch-params.sh
# Run
./src/zcashd

**Comment by madtomic** [comment]
You said... You have to checkout master.

command?

**Comment by heyrhett** [comment]
That should work. It didn't? What do your debug logs say?

**Comment by madtomic** [comment]
no bugs, it ran fine but on zcash main net

**Comment by heyrhett** [comment]
"git checkout master"

**Comment by madtomic** [comment]
I will do another clean virtual install with checkout master and see. I don't remember using checkout at all the first few times trying to get this to work.

**Comment by madtomic** [comment]
git checkout master - said I'm already on the master branch.

**Comment by heyrhett** [comment]
Are there ips in your zclassic.conf?

**Comment by madtomic** [comment]
I don't have it last time and the guide is for zcash and I don't think I used it. But it default to zcash mainnet anyway. Is there one for zclassic?

**Comment by madtomic** [comment]
What is a node for the zclassic chain?

**Comment by madtomic** [comment]
This is something needs to be address as well. It looks like it's using .zcash instead of .zclassic.

**Comment by madtomic** [comment]
I would address installation for newcomers that is trying to set up a zclassic wallet. So far, with what's on zclassic GitHub. They will end up with zcash. Not enough documentation on how to install zclassic and I would not reference anything to zcash guide. Better to write a separate for zclassic.

**Comment by madtomic** [comment]
Almost done building and I'm guessing mainnet.zclassic.org is the master node?

**Comment by madtomic** [comment]
It's working but just need to rename everything to zclassic. Thanks for your help.
