### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by PFFyodor** [z-classic/zclassic#112]
many peoples who use eleos GUI have problems at this time, we have deprecated version of daemon (zcld.exe), and dont have any way to get worked release.

I see some sources and relese what i can compile and use but only for debian linux?

We have wallets for windows.

What we can do? What we must to do? Have any roadmap?

**Comment by matthewjamesr** [comment]
Add in zclassic.conf file this line "disabledeprecation=1.0.10-1" it should sync. This is a temp fix until new exe's are available.
