### ISSUE TITLE
Syncing ZClassic blockchain when running full node

### ISSUE THREAD

**Issue by cloudydata** [z-classic/zclassic#117]
### Describe the issue
Trying to sync my ZClassic node

### Expected behaviour
Blockchain should continue syncing 

### Actual behaviour + errors
1) zcashd stops syncing and shuts down at block 209812
2) Messages: - Warning: This version will be deprecated at block height 209812, and will automatically shut down. You should upgrade to the latest version of Zcash. To disable deprecation for this version, set -disabledeprecation=1.0.10-1

### The version of Zcash you were using:
Zcash Daemon version v1.0.10-1-f94256c

### Machine specs:
- OS name + version: Ubuntu 16.04 LTS
- CPU: Core i7
- RAM: 32 GB
- Disk size: 2 TB
- Disk Type (HD/SDD): SDD
- Linux kernel version (uname -a): Linux pc415l 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc -version): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

**Comment by 2sgl** [comment]
add in zclassic.conf file this line "disabledeprecation=1.0.10-1" it should sync.

**Comment by matthewjamesr** [comment]
Closing this issue as resolved, reference the solution by @2sgl

**Comment by cloudydata** [comment]
thanks team.

after building with git master ---- everything worked fine

On Mon, Jan 1, 2018 at 11:40 PM, Matthew Reichardt <notifications@github.com
