### ISSUE TITLE
Merge fix for arch linux

### ISSUE THREAD

**Issue by abueide** [z-classic/zclassic#118]
Can we merge this fix for building on arch linux? https://github.com/zcash/zcash/pull/2545

**Comment by piraz** [comment]
I agree. It seems like the issue will fix fedora too. I'm having this issue:

```
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system-mt... no
configure: error: Could not link against boost_system-mt !     <<< THIS ONE
```

By zcash#2304 the real solution will be on zcash#2545.

**Comment by heyrhett** [comment]
If someone can make a pull request for zclassic

**Comment by piraz** [comment]
Help wanted tag on the issue?
