### ISSUE TITLE
$2500 Bounty: Fixing wallet issues

### ISSUE THREAD

**Issue by BlueSilver22** [z-classic/zclassic#119]
Hello all,

Here are the issues that need to be addressed:
1) We need to set up a way for the wallet to update the list of active wallet nodes in the zclassic.conf such that we can improve connectivity for all users. My understanding is we need to set up a node with insight API and make the wallet access the JSON from it.
A list of nodes are here: https://www.coinexchange.io/network/peers/ZCL

2) We need to get MORE nodes active. Not sure how we would go about doing this, but this way people can actually connect. I am guessing anyone running the wallet is running a node so if that is the case, then solving the above issue would resolve it.

3) We need to improve the installer/uninstaller and get a mac version of the wallet working. Right now, the installer is almost 1 GB due to the sprouting and proving keys found in the appdata ZCashParam folder. We need a way to make this installer smaller, perhaps it would download these files as it installs. Having it also download the blockchain would be fantastic. The fork by WaFeSc (https://github.com/WaFeSc/zclassic/releases/tag/1.2) seems to accomplish this with the blockchain, but the uninstaller is not capable of removing all the files when done either.

**Comment by DeviousPenguin** [comment]
Hello I think I may be able to solve the sprout-proving.key file issue, I should be able to make the installer below 100mb by making the wallet download the file if it's not found locally.

Is there a deadline for this or does it need to be done ASAP?

**Comment by BlueSilver22** [comment]
as soon as possible is best. We have two devs working on the other problems in the discord. message me on there and I will give you access to join the effort @jbrutwhat

**Comment by ac1dr3d** [comment]
BlueSilver22 bro we need 4 digit code to contact you on DC

**Comment by BlueSilver22** [comment]
try telegram instead: @jbrutwhat22

**Comment by DeviousPenguin** [comment]
Thanks, I've joined discord now, username is HypnoToad, I'll update you when I have something working, the installer should be around 100mb is all goes to plan :)

**Comment by AaronSmothers** [comment]
Think I might have a solution for getting more nodes active at scale. Discord @Desrix

**Comment by FlorinAndrei** [comment]
You should begin by making a list of action items that need to be worked on. Everyone agrees the installer needs to be improved, but what constitutes an actual improvement?

On Linux I've hit this brick wall: https://github.com/z-classic/zclassic/issues/114

On Windows 10 it simply doesn't work. zcashd keeps complaining about missing network stuff in the config directory, no matter what I add to the conf file.

You need to have an installer that performs the whole installation process from A to Z, and **TEST** it on a **fresh system**. At the very minimum, it needs to install the files in the correct locations, and create a conf file that actually works.

**Comment by FlorinAndrei** [comment]
Action item: https://github.com/z-classic/zclassic/issues/7
