### ISSUE TITLE
node doesn't sync .... help!

### ISSUE THREAD

**Issue by botio** [z-classic/zclassic#120]
Error massage :
2017-12-30 01:06:42 Loading addresses from DNS seeds (could take a while)
2017-12-30 01:06:42 msghand thread start
2017-12-30 01:06:43 0 addresses found from DNS seeds
2017-12-30 01:06:43 dnsseed thread exit
2017-12-30 01:06:50 socket recv error Connection reset by peer (104)
2017-12-30 01:06:51 socket recv error Connection reset by peer (104)
2017-12-30 01:06:51 connect() to 45.76.4.70:8133 failed after select(): Connection refused (111)
2017-12-30 01:06:52 connect() to 68.234.31.67:8133 failed after select(): No route to host (113)
2017-12-30 01:06:53 connect() to 52.14.116.113:8133 failed after select(): Connection refused (111)
2017-12-30 01:06:54 socket recv error Connection reset by peer (104)
2017-12-30 01:06:55 socket recv error Connection reset by peer (104)
2017-12-30 01:07:07 socket recv error Connection reset by peer (104)
2017-12-30 01:07:24 socket recv error Connection reset by peer (104)
2017-12-30 01:07:36 socket recv error Connection reset by peer (104)
2017-12-30 01:07:37 socket recv error Connection reset by peer (104)
2017-12-30 01:07:43 Adding fixed seed nodes as DNS doesn't seem to be available.
2017-12-30 01:07:43 connect() to 60.170.218.192:8133 failed after select(): Connection refused (111)
2017-12-30 01:07:44 connect() to 151.80.96.105:8133 failed after select(): Connection refused (111)
2017-12-30 01:07:44 socket recv error Connection reset by peer (104)

zclassic.conf:

addnode=dnsseed.zclassic.org
addnode=dnsseed.rotorproject.org
addnode=rotorproject.org
addnode=test-dnsseed.rotorproject.org
addnode=test-dnsseed.zclassic.org:8133
addnode=test-dnsseed.rotorproject.org:8133
addnode=89.142.65.151:8133
addnode=dnsseed.rotorproject.org:8133
addnode=104.207.149.241:8133
addnode=45.76.4.70:8133
addnode=68.234.31.67:8133
addnode=52.14.116.113:8133
addnode=136.243.50.159:8133
addnode=88.99.199.93:8133
addnode=13.91.45.250:8133
addnode=94.130.11.10:8133
addnode=37.187.167.145:8133

And I'm using Ubuntu 16.04 
I don't think anything working with the port 8133 ..... 

Please help me to fix it ~ thx

**Comment by 2sgl** [comment]
Try to run zcld with "-upnp" argument seems like router/internet connection problem.

**Comment by ruenchy** [comment]
i managed to get sync working by adding this to zclassic.conf
addnode=46.126.171.54
addnode=197.245.248.194
addnode=2a02:8388:8a01:1100:55e3:2656:54ff:fa6b
addnode=188.13.16.230
addnode=77.253.96.170
addnode=104.207.149.241
addnode=138.197.199.86
addnode=91.218.12.63
addnode=184.4.139.219
addnode=176.209.190.113
addnode=82.255.125.219
addnode=88.99.199.93
addnode=2a01:4f8:221:26dc::2
addnode=74.105.45.225
addnode=2a02:908:162:5efc:21f:bcff:fe09:5c62
addnode=87.103.195.162
addnode=68.234.31.67
addnode=78.94.32.196
addnode=158.69.183.22
addnode=120.27.230.83
addnode=138.68.48.247
addnode=2607:5300:60:ac0::1
addnode=89.142.65.151
addnode=198.100.147.192
addnode=60.170.218.192
addnode=79.98.144.29
addnode=2a01:4f8:212:1281::2
addnode=217.182.79.13
addnode=37.187.167.145
addnode=94.177.229.186
addnode=139.59.230.86
addnode=52.53.125.97
addnode=13.91.45.250
addnode=2400:6180:0:d0::17c6:e001
addnode=136.243.50.159
addnode=75.188.229.209
addnode=66.177.69.104
addnode=76.182.0.55
addnode=54.84.135.119
addnode=84.245.207.224
addnode=66.190.92.147
addnode=101.165.226.5
addnode=75.89.187.248
addnode=91.215.188.165
addnode=2001:0:9d38:953c:2c26:8d8:519b:e26f
addnode=217.166.97.38
addnode=76.24.40.93
addnode=68.60.109.183
addnode=172.249.44.225
addnode=73.65.184.66
addnode=187.181.14.1
addnode=151.202.33.171
addnode=64.39.73.2
addnode=96.29.230.162
addnode=135.0.251.101
addnode=109.15.167.1
addnode=2601:2c6:4a80:56a0:442e:aca6:1f4c:bb64
addnode=207.170.197.100
addnode=174.100.29.144
addnode=174.138.193.170
addnode=95.78.107.75
addnode=198.84.158.109
addnode=82.161.238.253
addnode=46.19.137.222
addnode=74.83.233.118
addnode=220.233.220.14
addnode=95.56.119.182
addnode=45.32.115.58
addnode=75.171.84.113
addnode=24.18.254.40
addnode=5.143.74.82
addnode=174.54.213.193
addnode=216.228.47.140
addnode=2a00:23c3:4aaa:b000:94af:ac88:35a2:542c
addnode=74.102.238.9
addnode=2a01:c50e:8824:d700:f05a:f723:fe3c:7923
addnode=68.104.58.47
addnode=98.230.121.23
addnode=88.24.78.71
addnode=82.24.216.124
addnode=98.168.137.138
addnode=47.62.219.193
addnode=24.228.56.53
addnode=209.181.61.219
addnode=50.82.45.123
addnode=209.194.2.18
addnode=71.231.198.79
addnode=208.107.54.154
addnode=162.197.26.236
addnode=184.54.109.70
addnode=188.167.68.208
addnode=196.52.2.32
addnode=118.92.193.153
addnode=87.123.236.140
addnode=64.223.106.104
addnode=94.78.207.1
addnode=82.17.137.87
addnode=142.129.74.38
addnode=73.42.176.102
addnode=67.183.29.123
addnode=70.162.238.217
addnode=217.75.222.33
addnode=24.17.178.164
addnode=2a02:a03f:4224:f300:81f6:f0fa:c30b:cb76
addnode=87.239.2.57
addnode=161.116.222.16
addnode=97.99.76.70
addnode=206.255.164.89
addnode=2001:0:9d38:90d7:24e7:2302:2314:5389
addnode=85.58.144.77
addnode=79.209.172.124
addnode=178.38.68.249
addnode=84.229.111.47
addnode=73.233.120.110
addnode=2001:8003:3898:8900:683a:32f4:3141:bb35
addnode=173.177.165.130
addnode=54.183.145.64
addnode=98.209.241.247
addnode=67.166.164.252
addnode=194.0.138.106
addnode=169.0.146.135
addnode=8.36.226.111
addnode=69.244.253.198
addnode=73.15.230.231
addnode=70.15.71.167
rpcport=8232

**Comment by ruenchy** [comment]
i got now 8 connections

**Comment by Klintistwood** [comment]
Hello all,

I have exactly the same problem. I have added the nodes suggested here but it doesn't change anything. I have tried to install the wallet on Ubuntu and Windows, same result. Could be some router related issue indeed but what should I change?

Thanks

**Comment by Klintistwood** [comment]
mmm now I see connections (2) and block height is increasing but swing wallet keeps on giving me the same error, the only thing that changed is the final part of the message (for input string: 4,15) and this figure is growing.

In the wallet I see zcashd status: running but resident stays at 0.0Mb

**Comment by ruenchy** [comment]
i can't say exctly whats your problem is, but i use "zcl windows wallet 1.1.0.3 by bitcoinz team"
https://github.com/bitcoinz-pod/bitcoinz-wallet/releases

**Comment by Klintistwood** [comment]
@ruenchy 
thanks I tried that one, managed to have it run for a few minutes (sync started) but now it crashes every time I try it :(

@2sgl I tried as you suggested but did not see any change

@botio did you solve your problem?

thanks all!

**Comment by botio** [comment]
yes, i did solve my proble by ........ waiting .... and didn't do anything else.... just wait for awhile for connection..... and get a cup of tea.

**Comment by Klintistwood** [comment]
@botio thanks! Could you post the content of your conf file?

**Comment by Klintistwood** [comment]
I tried this https://www.yougetsignal.com/tools/open-ports/ to see if port 8133 was open and it's closed. I checked my routers to open this port but it doesn't change anything. I directly connected to my modem (bypassing al routers) and port is still closed so there is nothing I can do to open it. I also tried my 4G connection with my smartphone and port is closed too.

Among the ones for who it's working here, can you check if this port is open for you? If you get the sync to work with the port closed, it means that the port is not the issue .

Thanks

**Comment by matthewjamesr** [comment]
I am closing this issue as it seems to be resolved. New dedicated default peers are coming online within the next 24 hours.
