### ISSUE TITLE
Mac doesn't read from configuration file

### ISSUE THREAD

**Issue by aribo** [z-classic/zclassic#121]
Installation on MacOS High Sierra.
Build is working.
Application opens but it doesn't read from configuration file that I copy in two locations & with two names (trying the known alternatives):
~/.zcash/zcash.conf
~/.zcash/zclassic.conf
~/.zclassic/zclassic.conf

Any suggestions?

**Comment by KaboomFox** [comment]
the file is located at `~/Library/Application Support/Zclassic/Zclassic.conf`
