### ISSUE TITLE
Cannot download ZClassic blockchain

### ISSUE THREAD

**Issue by vporton** [z-classic/zclassic#122]
We try to set ZClassic on our Ubuntu 14.04.5 amd64 server.

commit 36d1d21d493ab50a417787ae8684d3ee323acc35

I compiled zcash and start `./src/zcashd -printtoconsole`. Here is the config `~/.zclassic/zclassic.conf`:

    #gen=1
    connect=asia.zclassic.miningpoolhub.com:20575
    connect=ny1.minez.zone:3034
    connect=equihash.cryptobroker.io:3335
    connect=zcl.suprnova.cc:4042
    connect=zclassic.pool.mn:6041
    #addnode=minez.zone
    #addnode=pool.cryptobroker.io
    #addnode=zclmine.com
    #addnode=zclassic.miningspeed.com
    #addnode=zcl.suprnova.cc
    #addnode=dnsseed.zclassic.org
    #addnode=dnsseed.rotorproject.org
    rpcuser=XXX
    rpcpassword=XXX
    rpcport=8023
    p2pport=8033
    
    server=1
    #rpcbind=localhost
    #rpcconnect=localhost
    #showmetrics=0

Then I try to use stratum-mining: `~/stratum-mining# twistd -ny launcher.tac` repeatedly says:

    ...
    ERROR mining # CoinD downloading blockchain... will check back in 30 sec
    ...

More info (received after some time of zcashd running):

    # ~/zclassic/src/zcash-cli getinfo
    {
      "version": 1001051,
      "protocolversion": 170002,
      "walletversion": 60000,
      "balance": 0.00000000,
      "blocks": 0,
      "timeoffset": 0,
      "connections": 5,
      "proxy": "",
      "difficulty": 1,
      "testnet": false,
      "keypoololdest": 1514916287,
      "keypoolsize": 101,
      "paytxfee": 0.00000000,
      "relayfee": 0.00000100,
      "errors": ""
    }

What is the problem which prevents us to download blockchain?

**Comment by vporton** [comment]
Note that it was running around 10 hours with the same error (every 30 sec).

**Comment by matthewjamesr** [comment]
Why are your `addnode=` commented out? That is the proper way to get a peer added to `peers.dat`.

**Comment by vporton** [comment]
because I got errors about non-functional nodes

**Comment by interbiznw** [comment]
Try these new nodes we started

addnode=149.56.129.104
addnode=51.254.132.145
addnode=139.99.100.70
addnode=50.112.137.36
addnode=188.166.136.203
addnode=159.89.198.93

**Comment by vporton** [comment]
```
connect() to 51.254.132.145:8033 failed after select(): Connection refused (111)
connect() to 139.99.100.70:8033 failed after select(): Connection refused (111)
connect() to 50.112.137.36:8033 failed after select(): Connection refused (111)
connect() to 188.166.136.203:8033 failed after select(): Connection refused (111)
connect() to 159.89.198.93:8033 failed after select(): Connection refused (111)
```

**Comment by aomelche** [comment]
The following just worked for me.

addnode=149.56.129.104:8133
addnode=51.254.132.145:8133
addnode=139.99.100.70:8133
addnode=50.112.137.36:8133
addnode=188.166.136.203:8133
addnode=159.89.198.93:8133

**Comment by vporton** [comment]
Thank you very much. With this settings it started to work.

I used different servers before and it didn't work. So I previously concluded that the problem was not in specifying wrong servers. I was wrong.
