### ISSUE TITLE
Unexpected error occured when updating the GUI Wallet state...

### ISSUE THREAD

**Issue by Jugeen** [z-classic/zclassic#125]
I get this error while opening ZClassic Wallet with the jar-file:

"Unexpected error occured when updating the GUI Wallet state. Please ensure that ZCash Deamon is running"..

i started zcashd.exe before i started the wallet. and zcashd-status is "Running".

https://picload.org/view/ddolllwl/zcash_wallet_prob.jpg.html

please help

**Comment by Dontorpedo** [comment]
same

**Comment by rogerrogeryau** [comment]
same issue. mine happened after incomplete (initial) syncing to the server.

**Comment by x0xa** [comment]
same
Windows 7 x64

**Comment by smfukaya** [comment]
Create a BAT file (ZClassicSwingWalletUI.bat) in the same folder. Edit it with notepad and add the following line in order to change the regional settings to English (problem could be related to your decimal separator).

java -Duser.language=us-EN -jar ZClassicSwingWalletUI.jar
