### ISSUE TITLE
How do i send Zclassic from my paper wallet to somewhere else?

### ISSUE THREAD

**Issue by barrelroll1** [z-classic/zclassic#128]
I recently set up my Zclassic paper wallet and funded it but can't figure out how to make transfers to other paper wallets and exchanges. Please advice.

**Comment by Blantanamera** [comment]
Hi, I've got the same problem, did you figure it out by now? 
Best
B

**Comment by barrelroll1** [comment]
Yes. You have to download the latest Zclassic wallet and select "import single private key". This sends everything in your paper wallet to your Zclassic wallet, then you can send it to an exchange or wherever else you would like to.

**Comment by Blantanamera** [comment]
Hi, but you’ve got PC or Mac? I've got Mac.

On 12 Jan 2018, at 18:30, barrelroll1 <notifications@github.com> wrote:

Yes. You have to download the latest Zclassic wallet and select "import single private key". This sends everything in your paper wallet to your Zclassic wallet, then you can send it to an exchange or wherever else you would like to.

**Comment by Cyrano3C** [comment]
Is there some way to import the private key into the Electrom wallet?

**Comment by Blantanamera** [comment]
Hi,
sure thing, when you set up a new wallet you choose 1 of 4 options (I don’t remember which one,
but you’ll figure it out easily) and enter your keys. You set up password and it’s done.
Peace,
M

On 23 Feb 2018, at 00:17, Cyrano3C <notifications@github.com> wrote:

Is there some way to import the private key into the Electrom wallet?

**Comment by Cyrano3C** [comment]
That did the trick. Thanks M!
Peace.
