### ISSUE TITLE
Transferring Zclassic from a web wallet.

### ISSUE THREAD

**Issue by Blantanamera** [z-classic/zclassic#130]
Hi, 
I cannot transfer Zclassic FROM a web wallet provided. Money just come IN.
How can I transfer from this wallet? I've got Macbook Pro. Thanks a lot!
Best,
B

### Expected behaviour
Transferring Zclassic FROM my Zclassic wallet (http://zclassicexplorer.com/).

### Actual behaviour + errors
I can't see any way to SEND Zclassic from my Zclassic wallet.

### The version of Zcash you were using:
Zclassic.

### Machine specs:
- macOS High Sierra
- Chrome

**Comment by Saifoo** [comment]
Which web wallet? I don't think there is any such. 

There is a beta version of ZClassic wallet for Mac ([Eleos](https://github.com/HarrKxx/eleos/releases)) which you can use to store your ZClassic.

**Comment by Blantanamera** [comment]
Hi,
here it is: http://zclassicexplorer.com/ <http://zclassicexplorer.com/>
B.,
M

On 23 Jan 2018, at 20:10, Saif Ur Rehman <notifications@github.com> wrote:

Which web wallet? I don't think there is any such.

There is a beta version of ZClassic wallet for Mac (Eleos <https://github.com/HarrKxx/eleos/releases>) which you can use to store your ZClassic.

**Comment by Saifoo** [comment]
This is not a wallet. It is just a block explorer. It is used to track transactions.

**Comment by Blantanamera** [comment]
OK, I’ve got this as well: https://zclassicpaperwallet.com/ <https://zclassicpaperwallet.com/>
There’s a public and secret key in it, I’ve dowloaded them but don’t know how to use it.
Money just come in, but how can I send it? Thanks.
B.,
M

On 23 Jan 2018, at 20:15, Saif Ur Rehman <notifications@github.com> wrote:

This is not a wallet. It is just a block explorer. It is used to track transactions.

**Comment by Saifoo** [comment]
Use the public key to receive ZClassic. From wherever you are sending ZCL, use your public key as a sending address.

**Comment by Blantanamera** [comment]
OK, public key either for receiving and sending?

On 23 Jan 2018, at 20:51, Saif Ur Rehman <notifications@github.com> wrote:

Use the public key to receive ZClassic. From wherever you are sending ZCL, use your public key as a sending address.

**Comment by Saifoo** [comment]
Let me explain in a simple manner. What do you use to receive emails from people? Yes, email address. For instance your email is blantanamera@gmail.com. Now if I wanted to send an email to you I will use this email address which is public. If you want to send an email to me, you will sign in on Gmail (client) with your password to send me an email. This time you will use my email address (say: saif@gmail.com) to send me emails. 

Sending and receiving crypto currencies work in a similar manner. If I want to send ZCL to you, I will use your public address to send ZCL and vice versa. The private/secret key is like your password. You unlock your wallet (account) with this key to access your funds. NEVER EVER share your secret/public key with anyone. 

You said "Money just come in.." Could you please explain how you received this money?

**Comment by Blantanamera** [comment]
I’ve bought it and sent it to my public address.

On 23 Jan 2018, at 21:05, Saif Ur Rehman <notifications@github.com> wrote:

Let me explain in a simple manner. What do you use to receive emails from people? Yes, email address. For instance your email is blantanamera@gmail.com <mailto:blantanamera@gmail.com>. Now if I wanted to send an email to you I will use this email address which is public. If you want to send an email to me, you will sign in on Gmail (client) with your password to send me an email. This time you will use my email address (say: saif@gmail.com <mailto:saif@gmail.com>) to send me emails.

Sending and receiving crypto currencies work in a similar manner. If I want to send ZCL to you, I will use your public address to send ZCL and vice versa. The private/secret key is like your password. You unlock your wallet (account) with this key to access your funds. NEVER EVER share your secret/public key with anyone.

You said "Money just come in.." Could you please explain how you received this money?

**Comment by findSaif** [comment]
Do you have the private key of that public address?

**Comment by Blantanamera** [comment]
Yes.

On 23 Jan 2018, at 21:28, Saif Rehman <notifications@github.com> wrote:

Do you have the private key of that public address?

**Comment by ch4ot1c** [comment]
Please try out https://github.com/BTCP-community/electrum-zcl/releases/tag/Z!1.0.1 - our Electrum wallet for Mac. During wallet setup, there is an option to 'Import Private Keys'
