### ISSUE TITLE
No zcashd and zcash-cli binaries available on github for Linux and Windows outside of the wallet installer

### ISSUE THREAD

**Issue by Scottrock** [z-classic/zclassic#132]
Only a wallet.exe release is available - this is not needed for people just upgrading an existing wallet, or who want to use the command line.

### Can you reliably reproduce the issue?
1. Look on git
2. No releases available

### Expected behaviour
1. look on git
2. Win and Linux binaries in a zip file on the releases tag

### Actual behaviour + errors
1. Look on git
2. No releases available

- OS Windows 10 and Linux

**Comment by nimbosa** [comment]
v1.0.10-1 official https://github.com/z-classic/zclassic/releases

v1.0.14 dev branch https://github.com/ZclassicDev/zclassic/releases
