### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by jc23424** [z-classic/zclassic#134]
Test suite does not pass after a checkout and build.
After some examination with bisect, this appears to have been introduced by this commit: 
https://github.com/z-classic/zclassic/commit/d753a0c7901727b51ab9b3fa7c84d147275662b2

**Comment by zanethomas** [comment]
Have been informed that I was not running the entire test suite (newbie) and doing so demonstrated there is at least one other problem to be found and fixed. Will commit when fixed.

**Comment by zanethomas** [comment]
I believe my current pull requests resolve all the test issues, with one failing test temporarily disabled as described in my latest pull request.
