### ISSUE TITLE
Mac Wallet

### ISSUE THREAD

**Issue by jomina11** [z-classic/zclassic#136]
My ELEOS Mac wallet does not give me the option under the file dropdown to import my paper wallet private keys see screenshot. Can you advise me I don't like having money on paperwallet 
<img width="316" alt="screen shot 2018-01-16 at 12 41 48" src="https://user-images.githubusercontent.com/29247517/34989574-fd84404e-faba-11e7-84ef-4616423697c3.png">

**Comment by ch4ot1c** [comment]
The Electrum mac wallet does support importing -
https://github.com/BTCP-community/electrum-zcl/releases/tag/Z!1.0.1
