### ISSUE TITLE
zcl balance shows correct but 0 confirmations . cant send out now

### ISSUE THREAD

**Issue by aakashshiv** [z-classic/zclassic#147]
I have 2 ZCL addresses in my wallet . both show correct balances . One address however shows 0 confirmations for the past 6 months. . The total wallet balance is correct. Explorer also shows correct balance .  I cannot send out from this address. Pls help.
![screenshot 27](https://user-images.githubusercontent.com/29179222/35385892-f253a52a-01ef-11e8-9e87-51caa90979a3.png)
![screenshot 26](https://user-images.githubusercontent.com/29179222/35385893-f27b5a52-01ef-11e8-9c3e-7c83270c6480.png)

**Comment by ch4ot1c** [comment]
http://explorer.zclmine.pro/address/t1a9wmfTXAdPjcLp8tUwEdJe8ZR1NZN2ugZ
The block explorers never lie! Your funds are at the addr and confirmed.

Get that private key from Eleos, and then try importing it into https://github.com/BTCP-community/electrum-zcl/releases/tag/Z!0.1.0 . Does it appear here? If so (it should), hold on tight to that private key and that's it 👍

**Comment by aakashshiv** [comment]
Thanks mate
I got it working. The config.dat file was old and wallet wasn't synced.
Cheers.

**Comment by ch4ot1c** [comment]
You're welcome
