### ISSUE TITLE
Zcashd fails to build Ubuntu 17.10 configure: error: Could not link against boost_system-mt !

### ISSUE THREAD

**Issue by NickRHill** [z-classic/zclassic#148]
Compilation stops on 
configure: error: Could not link against boost_system-mt !

cat /etc/issue
Ubuntu 17.10 \n \l

uname -m
x86_64

Other Z-related daaemons compile on system - build environment is sane and has expected libraries. 

sudo apt-get install \
      build-essential pkg-config libc6-dev m4 g++-multilib \
      autoconf libtool ncurses-dev unzip git python \
      zlib1g-dev wget bsdmainutils automake

Everything xxxx is the newest version

cd zclassic
./zcutil/build.sh -j$(nproc)

...
checking for miniupnpc/upnperrors.h... yes
checking for main in -lminiupnpc... (cached) yes
checking for boostlib >= 1.20.0... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system-mt... no
configure: error: Could not link against boost_system-mt !

[zclassicbuildlog.txt](https://github.com/z-classic/zclassic/files/1670507/zclassicbuildlog.txt)

**Comment by josephnicholas** [comment]
@NickRHill Already fixed in [#124](https://github.com/z-classic/zclassic/pull/124). Please pull changes and rebuild again.

**Comment by NickRHill** [comment]
I can confirm this resolves the issue. 

Thanks.
