### ISSUE TITLE
Error connecting to server when loading the Zclassic GUI on windows pls HELP

### ISSUE THREAD

**Issue by busyjordy** [z-classic/zclassic#151]
I am unable to open my wallet for a few days. Every time I get this error message and the app shuts so I can't get access to my wallet at all. No other issues on my PC so I don't think it's a hack, some connectivity error it seems. Can you advise please.
![454545](https://user-images.githubusercontent.com/36042520/35936645-1eafaaca-0c44-11e8-9fdc-310c74a59e4d.JPG)

**Comment by busyjordy** [comment]
I did have an older Eleos version which I think I removed but when I installed this wallet it showed me my older addresses and transactions, so there must have been cookies and other leftover files from Eleos which was not an issue for the first week. But now I think this may be the reason why my wallet doesn't open anymore, did I mess up something?

**Comment by ch4ot1c** [comment]
%APPDATA%\Zclassic should contain `wallet.dat` - does it?

C:\Users\You\AppData\Roaming\Zclassic\

**Comment by Joeycrabs** [comment]
I have the same issue I do have my wallet.dat file backed up but how can i open it?

**Comment by Remet89** [comment]
I have the same issue as well. I've got 2 separate wallets on 2 different machines and both give the same error ''Couldn't connect to server''. One of the wallets was even running and I restarted it to see if its an isolated issue and I got the same error. I'm using ''zclassic_winv1.0.5_installer ''. Tried a fix I found on reddit but that didn't work. Reddit fix [https://www.reddit.com/r/ZClassic/comments/7v3rec/zclassic_swing_wallet_cant_connect_to_the_server/](url)

**Comment by Remet89** [comment]
Fixed it. Back up your Zclassic folder at users/user/AppData/Roaming/. Delete ''blocks'' and ''chainstate'' folder. Start up and wait for the blockchain to sync. At first your balance will be 0 don't freak out. Make sure you back up the folder incase something goes wrong.

**Comment by lodotek** [comment]
Why does this happen?

**Comment by MarceloFx35** [comment]
Hi Jordan and Remet89, I finally fixed my issue ( I had the same one), you guys are awesome.

**Comment by omarrand** [comment]
Hi solution does not open the Zclaccic wallet
not connected can help me plz
