### ISSUE TITLE
testnet and faucet

### ISSUE THREAD

**Issue by kiahmed** [z-classic/zclassic#154]
what is addnode or seednode for testnet ? Also is there any faucet to get some test coins?

**Comment by analiser** [comment]
35.224.210.173:18233

**Comment by kiahmed** [comment]
thank..its connected ,but running for quite a while.. still no data.. is it normal?
{
    "result": {
        "version": 1001051,
        "protocolversion": 170002,
        "walletversion": 60000,
        "balance": 0,
        "blocks": 0,
        "timeoffset": 0,
        "connections": 1,
        "proxy": "",
        "difficulty": 1,
        "testnet": true,
        "keypoololdest": 1518739920,
        "keypoolsize": 101,
        "paytxfee": 0,
        "relayfee": 0.000001,
        "errors": ""
    },
    "error": null,
    "id": 1
}

**Comment by analiser** [comment]
please use this one for tetnet

https://github.com/Mrwh0/zclassic

On Feb 15, 2018 7:48 PM, "kiahmed" <notifications@github.com> wrote:

thank..its connected ,but running for quite a while.. still no data.. is it
normal?
{
"result": {
"version": 1001051,
"protocolversion": 170002,
"walletversion": 60000,
"balance": 0,
"blocks": 0,
"timeoffset": 0,
"connections": 1,
"proxy": "",
"difficulty": 1,
"testnet": true,
"keypoololdest": 1518739920,
"keypoolsize": 101,
"paytxfee": 0,
"relayfee": 0.000001,
"errors": ""
},
"error": null,
"id": 1
}

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/z-classic/zclassic/issues/154#issuecomment-366106606>,
or mute the thread

**Comment by Mrwh0** [comment]
https://github.com/Mrwh0/zclassic
use this one for testnet 

any need test coins please set an issue with your testnet address in Mrwh0 repo

**Comment by kiahmed** [comment]
not got this , stuck at block 594 ..is it normal on testnet?
{
    "result": {
        "version": 1001051,
        "protocolversion": 170002,
        "walletversion": 60000,
        "balance": 0,
        "blocks": 594,
        "timeoffset": 0,
        "connections": 2,
        "proxy": "",
        "difficulty": 1067.785802366007,
        "testnet": true,
        "keypoololdest": 1518813861,
        "keypoolsize": 101,
        "paytxfee": 0,
        "relayfee": 0.000001,
        "errors": ""
    },
    "error": null,
    "id": 1
}

**Comment by kiahmed** [comment]
* now.. also here is my address, please send some test zlc on my way
ztXG8LthdvbxwV6dFUtyRjBjs8Eacxc5MMCpJ4t2wE3tgqLEJWMoHxb73TDFVKwSvfJsjyxL5qEPrkN2JhDgs8sUbz4qaEo

**Comment by Mrwh0** [comment]
yes is normal because no one in solving next block. we seting up a testnet miming pool to solve that . only your cpu in network hashrate. =) 16 sol/s

**Comment by kiahmed** [comment]
still haven't received any

**Comment by Mrwh0** [comment]
sry for delay im working on last nasa rocket  launch so im little busy give
me few hours

**Comment by kiahmed** [comment]
tmLjE91zzF1EFDHCa9tAJYqpS1CiaGrM6S5

**Comment by Mrwh0** [comment]
please all testnet users be advice last chain stuck on block 584

**Comment by Mrwh0** [comment]
please all testnet users be advice last TESTNET chain stuck on block 594 due to main server failure.  timestamp is not valid anymore.  we working to set up new testnet chain ASP .

**Comment by kiahmed** [comment]
did you guys fixed it yet? if there is not testnet and taken down as wish, how dev community will work?

**Comment by ch4ot1c** [comment]
dnsseed.testnet.zclassic.org

**Comment by kiahmed** [comment]
added like this..unfortunately not work , it shows 1 connection and 0 blocks, at least it was stuck at 594 block before

addnode=dnsseed.testnet.zclassic.org

**Comment by xianxiongwang** [comment]
Someone is ok？it doesn't work.

2018-04-10 07:51:19 tor: Not connected to Tor control port 127.0.0.1:9051, trying to reconnect
2018-04-10 07:51:20 Added 1 addresses from 203.161.230.171: 0 tried, 1 new
2018-04-10 07:51:20 1 addresses found from DNS seeds
2018-04-10 07:51:20 dnsseed thread exit
2018-04-10 07:51:21 tor: Error connecting to Tor control socket
2018-04-10 07:51:21 tor: Not connected to Tor control port 127.0.0.1:9051, trying to reconnect
2018-04-10 07:51:23 trying connection 4.36.66.178:18233 lastseen=97.6hrs
2018-04-10 07:51:25 tor: Error connecting to Tor control socket
2018-04-10 07:51:25 tor: Not connected to Tor control port 127.0.0.1:9051, trying to reconnect
2018-04-10 07:51:28 connection to 4.36.66.178:18233 timeout
2018-04-10 07:51:30 tor: Error connecting to Tor control socket
2018-04-10 07:51:30 tor: Not connected to Tor control port 127.0.0.1:9051, trying to reconnect
