### ISSUE TITLE
Issue with Eleos wallet 0.1.0

### ISSUE THREAD

**Issue by lolotica911** [z-classic/zclassic#163]
I used my Eleos wallet to receive ZCL from Cryptopia before and it worked well but I tried again last night and it seems problem. Status from Cryptopia shows "complete" and I checked transaction ID on Zclassic block explorer, it seems OK but the coins haven't arrived my wallet yet.

I open Eleos, the connection sometimes show 0, 1, 2.. sync 99-99.xx%. 

Any suggestion please?

**Comment by ch4ot1c** [comment]
Try the new Desktop Wallet, with its daemon.
