### ISSUE TITLE
$5000 bounty to solve the Bittrex problem

### ISSUE THREAD

**Issue by keweees** [z-classic/zclassic#168]
I give $5000 in bitcoins who can solve this problem:
https://support.bittrex.com/hc/en-us/articles/360001271272

https://github.com/zcash/zcash/issues/2446
https://github.com/zcash/zcash/issues/2448

zcl is dying I have invested everything in it and the price fall and the devs just talk about bitcoin private and have abandoned this!!! :(

**Comment by csulmone** [comment]
Merged in https://github.com/z-classic/zclassic/pull/166

**Comment by gstuto** [comment]
i second this merge in #166

**Comment by mike223** [comment]
Hello keweees. Seems ZCL had already lost most of its price when you wrote here. If you are interested to restart ZCL we can discuss our options: mike223@discardmail.de

**Comment by zusrt** [comment]
do not worry
zclassic is Mineable
and only 16% of the mine is mined
about the code  just follow zcash will be OK
If the developer can determine its life and death
Then it is not decentralized

**Comment by zusrt** [comment]
https://github.com/nimbosa/zclassic/releases/tag/v1.0.14-testing
maybe help

**Comment by nimbosa** [comment]
please test and review this release last January 29, 2018 @keweees : https://github.com/ZclassicDev/zclassic/releases

commit: https://github.com/ZclassicDev/zclassic/commit/39862b36ef054f7689e7c0c73acbc63f93db2328

**Comment by nimbosa** [comment]
bounty can be used for further development and support of Zclassic 😊
