### ISSUE TITLE
More ZClassic node?

### ISSUE THREAD

**Issue by madtomic** [z-classic/zclassic#17]
Any more nodes being added?
I have no connections and it's stuck on block 4124

**Comment by joshuayabut** [comment]
I just put another one up. Is it working now?

**Comment by joshuayabut** [comment]
Try putting addnode=dnsseed.rotorproject.org in your config file.

**Comment by khoubaibc** [comment]
hi i have added node zcl.mining.tn to my config file

`addnode=zcl.mining.tn` it's ok ?

**Comment by joshuayabut** [comment]
Hello,

I'm not able to confirm that there is a node operating on that address.

But you should be able to add this and get it to work:
addnode=dnsseed.zclassic.org
addnode=dnsseed.rotorproject.org

I'm closing this out since the nodes are live and running.
