### ISSUE TITLE
deposit no show up in wallet

### ISSUE THREAD

**Issue by juanchingli77** [z-classic/zclassic#170]
### Describe the issue
Can you help check why my withrawn from exchange to my wallet not show up.I did 2 times before ,it success.But this time not .

2018-03-02 00:27:13 | ZCL | 99.91407403 | 0.00100000 | t1QUcL33WMKx3zgTDrsvffhqagMph52Ddy4 f12350121b5d8531fed55d6983377352d7e21f13b23c333cbfd919630f067f95
-- | -- | -- | -- | --

#### If so, please list the steps to reproduce below:
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour + errors
Tell us what happens instead including any noticable error output (any messages displayed on-screen when e.g. a crash occurred)

### The version of Zclassic / Zcash you were using:
Run `zcashd --version` to find out

### Machine specs:
- OS name + version:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):
- Linux kernel version (uname -a):
- Compiler version (gcc -version):

### Any extra information that might be useful in the debugging process.
This includes the relevant contents of `~/.zclassic/debug.log`. You can paste raw text, attach the file directly in the issue or link to the text via a pastebin type site.
Please also include any non-standard things you did during compilation (extra flags, dependency version changes etc.) if applicable.

### Do you have a back up of `~/.zclassic` directory and/or take a VM snapshot?
- Backing up / making a copy of the `~/.zclassic` directory might help make the problem reproducible. Please redact appropriately.
- Taking a VM snapshot is really helpful for interactively testing fixes

**Comment by ch4ot1c** [comment]
http://zclassicexplorer.com/insight/address/t1QUcL33WMKx3zgTDrsvffhqagMph52Ddy4
