### ISSUE TITLE
Equihash to Yiimp

### ISSUE THREAD

**Issue by goodthebest** [z-classic/zclassic#172]
Dev
Could you please integrate Equihash algo to Yiimp so that we can mine Zclassic with Yiimp? Perhaps it will be nice if you developer can place a pull request to add equihash into yiiimp
https://github.com/goodthebest/yiimp

**Comment by nimbosa** [comment]
https://github.com/tpruvot/yiimp/commit/7d039a1eeaab05104b84ea5b46bd0cb4d6093b14
