### ISSUE TITLE
HELP NEEDED!!! Transferred ZCL to cryptopia 2 months ago and it still isnt in my accoun. What should i do?

### ISSUE THREAD

**Issue by spiz888** [z-classic/zclassic#174]
Hi guys. I need some help and would appreciate any response. I sent ZCL to cryptopia from my elect-rum wallet 2 months ago, and i still havent receieved it in my cryoptia account. I think it may be a problem on my electrum wallet. I have double checked the deposit address and its all good . 
I have attached a screen shot of the wallet transaction. Can anyone help me please?
Can you see a problem ? anyone know what i should do? 

Thanks 
<img width="754" alt="screen shot 2018-04-25 at 2 50 12 am" src="https://user-images.githubusercontent.com/35133160/39202219-9b6760d6-4834-11e8-812f-d22486829a42.png">

**Comment by WaFeSc** [comment]
It's confirmed so should be at cryptopia...is the address correct? Check if
cryptopia moved the coins out of your account on the blockchain...


Op di 24 apr. 2018 19:01 schreef spiz888 <notifications@github.com>:

**Comment by spiz888** [comment]
thanks wafe. How can i check if cryptopia have moved my coins onto the blockchain?

**Comment by WaFeSc** [comment]
Fill the destination in the block explorer ...and see if there is some
left...

Op di 24 apr. 2018 19:30 schreef spiz888 <notifications@github.com>:

**Comment by spiz888** [comment]
yep its showings my ZCL address at cryptopia to be 181, but my balance is showing 0 (at cryptopia) So this would be mean its a problem on cryptopias end?

<img width="1274" alt="screen shot 2018-04-25 at 3 38 44 am" src="https://user-images.githubusercontent.com/35133160/39204169-69ee63aa-483a-11e8-9776-18306e2cc9ca.png">


<img width="1274" alt="screen shot 2018-04-25 at 3 38 44 am" src="https://user-images.githubusercontent.com/35133160/39204160-61eac982-483a-11e8-838c-93dadabfb8df.png">
