### ISSUE TITLE
Making a zclassic forum

### ISSUE THREAD

**Issue by faddat** [z-classic/zclassic#18]
Hi, I'd like to make a zcassic forum.  That way you can take zcash forum off of the repo.

**Comment by heyrhett** [comment]
Great, please do!  It's probably a good idea to ask for feedback in our slack channel.

**Comment by faddat** [comment]
Sure.  There's only one real question though:

Discourse
Or
Nodebb

**Comment by joshuayabut** [comment]
Forums are up http://zcltalk.tech/ although missing HTTPS support.
