### ISSUE TITLE
Clarity about the ZCash Fork

### ISSUE THREAD

**Issue by nxd0main** [z-classic/zclassic#180]
Hello ZClassic Team, 

I am just trying, for clarity in a document that I am writing, to understand how ZClassic is a 'fork' of ZCash. I can see, very transparently, that you are a github code 'fork' of ZCash. 

First of all, thank you for that transparency, not all cryptocurrencies are so clear about forking repositories in github. 

However, from what I can see, if you were actually a hardfork (in the cryptocurrency Proof-of-Work sense, as opposed to the repository fork sense), then you would share the same Genesis Block Hash and the corresponding Merkle Root that formed part of the input to generate the Genesis Block Hash. 

However, if I look at the chainparams.cpp of ZCash and ZClassic, I can see that the former has: 
        assert(consensus.hashGenesisBlock == uint256S("0x00040fe8ec8471911baa1db1266ea15dd06b4a8a5c453883c000b031973dce08"));
        assert(genesis.hashMerkleRoot == uint256S("0xc4eaa58879081de3c24a7b117ed2b28300e7ec4c4c1dff1d3f1268b7857a4ddb"));

and the latter (IE ZClassic) has 

        assert(consensus.hashGenesisBlock == uint256S("0x0007104ccda289427919efc39dc9e4d499804b7bebc22df55f8b834301260602"));
        assert(genesis.hashMerkleRoot == uint256S("0x19612bcf00ea7611d315d7f43554fa983c6e8c30cba17e52c679e0e80abf7d42"));

*

So can you confirm that my reasoning is sound, and that is, you are a github repository code fork of ZCash but not a hardfork of ZCash. 

Kind Regards,

**Comment by nimbosa** [comment]
yes your facts and analysis are correct @nxd0main , Zclassic has unique genesis block and it is NOT from zcash, ZCL genesis block is now shared by ZenCash/Horizen, Bitcoin Private and ANON which are all hardforks from Zclassic, this should make it clear for everybody else, Zclassic strives to be as open & transparent as always

Thanks for asking!

**Comment by nxd0main** [comment]
Hi @nimbosa, Thank you so much for the clarity and the prompt response. Glad to see others currencies are using your genesis block. I must say it is nice to get a response from a core development community member so promptly. I am impressed, I am generally met with radio silence with a lot of other queries I've made.
