### ISSUE TITLE
The partner instant exchange SimpleSwap.io

### ISSUE THREAD

**Issue by SimpleSwap** [z-classic/zclassic#195]
Hi,

I am Nicolas, the manager at SimpleSwap.io, an instant cryptocurrency exchange.

We present a simple and easy-to-use platform that works without registration and limits and allows users to make swaps in just two clicks.

We successfully support ZCL on our service for a long time and we have been exchanging ZCL for more than 200 coins to our customers. I tried to find contact with your team but without results.

I'm sorry that I invaded here, but maybe you can tell me where I can turn. I would like to make contact so we can have an interaction.

**Comment by nimbosa** [comment]
Hello @SimpleSwap, I am the current maintainer of this repo and organization. Have you tried reaching out on [discord](https://discord.gg/45NNrMJ)? I am not on that channel now but it is our most active and most helpful channel so far and I am restoring access to them ASAP. See you there!
