### ISSUE TITLE
Zcashd graphic maxes at 8 connections

### ISSUE THREAD

**Issue by mountaindrifter** [z-classic/zclassic#22]
When running ~/zclassic/./src/zcashd (in non daemon mode), the graphic correctly shows the amount of connections up to 8. I have 70 active connections via zcash-cli, yet the zcashd graphic still shows 8.

**Comment by joshuayabut** [comment]
Hello have you tried setting "maxconnections=" in the zclassic.conf file?

**Comment by mountaindrifter** [comment]
Josh, yes. When I set the max connections to a higher limit the zcashd metrics display maxes out at 8 connections even though I have more connections. I have not had time to look, but I wonder if printNetworkStats() in metrics.cpp should rely on vNodes.size() directly. Like I said, I have not looked and I am probably way off base. I realized earlier I may just have a beefed build because another machine seems to reporting correctly. I will rebuild from the master later and update.

**Comment by mountaindrifter** [comment]
Strangely gethconnectionscount, which I believe also calls vNodes.size(), was reporting the correct number of coinnections

**Comment by mountaindrifter** [comment]
Welp, looks like I am crazy. I rebuilt and everything seems to be working. I can't explain why it was doing that earlier. Closing

**Comment by avisrivastava254084** [comment]
@joshuayabut Where is the zclassic.conf file? I placed your mentioned argument zcash.conf but the max connections seem to be 8 and not 16(the value that I put).
