### ISSUE TITLE
Change the ASCII message for Zclassic information and their logo colors.

### ISSUE THREAD

**Issue by emptydisk** [z-classic/zclassic#3]
![Picture](https://cloud.githubusercontent.com/assets/23296475/20039813/3f2ce180-a44b-11e6-8f8f-a3b68f08e251.png)

It is interesting if this logos are changed for Zclassic branding. At least colors, to don´t be confused on which Blockchain are you working on.

**Comment by emptydisk** [comment]
It can be changed here:
https://github.com/z-classic/zclassic/blob/master/src/metrics.h
Using this tool: 
https://github.com/hit9/img2txt

**Comment by heyrhett** [comment]
Thank you, please submit a pull request and we will review.

**Comment by hairetikos** [comment]
i have done a pull request for this now, i used the img2txt bundled with caca-utils, the others don't seem to have the same options for rendering.

**Comment by joshuayabut** [comment]
https://github.com/z-classic/zclassic/pull/32/commits/f6dc8ccec25e74743f5f9dbacd4d55e8087e6ca3
