### ISSUE TITLE
Review/purge slow start and founder's fee artifact

### ISSUE THREAD

**Issue by mountaindrifter** [z-classic/zclassic#34]
The test suite is passing for 1.0.3, but we need to review the code for 1.0.4 to be sure the artifacts from founder's fee and slow start are removed and properly updated throughout the src

Likewise, we need to reveiw the values in  ~/zclassic/src/test/main_tests.cpp to be sure the BOOST check values are correct as well as all of the definitions/arrays that it refers to.

specifically, check in main_tests.cpp:
// Mining slow start
// Remainder of first period
// Regular mining

**Comment by heyrhett** [comment]
A reason to not purge is it makes merging easier from zcash.

**Comment by joshuayabut** [comment]
Marking this as closed since all tests are passing as of 1.0.4.
