### ISSUE TITLE
How exactly was the genesis block created?

### ISSUE THREAD

**Issue by johnrrush** [z-classic/zclassic#40]
This is a question rather than an issue but I can't seem to find a clear answer anywhere. 

Before buying into the coin I'd like to understand exactly how the genesis block was created, I'm hoping the dev who did it has time to answer :) What exact steps were taken? 

I understand the same parameters were used for Zclassic as Zcash's ceremony, but what specifically does that mean? (code references greatly appreciated)

Thanks!

**Comment by joshuayabut** [comment]
Hello I'm the dev that mined the Genesis block.. I'm not sure what exactly you are asking but here's an example of the parameters that needed to be changed for the testnet genesis block.

https://github.com/z-classic/zclassic/commit/9ab02577ce503317e6bdb560b1d6f9146b2fe872

**Comment by heyrhett** [comment]
People often confused the "Genesis Block" with the Trusted Parameters required for ZK-SNARKs.

Z-cash had a trusted setup ceremony.  Peter Todd goes into his part here:
https://petertodd.org/2016/cypherpunk-desert-bus-zcash-trusted-setup-ceremony

Zclassic uses, bit-for-bit, exactly the same Trusted Parameters as Zcash, which is also the same thing Peter Todd suggests:
https://www.reddit.com/r/ZClassic/comments/5bbpmr/we_should_invite_petertodd_to_our_trusted_setup/

You can see the file here is unchanged:
https://github.com/z-classic/zclassic/blob/master/zcutil/fetch-params.sh

**Comment by thghdbs** [comment]
How was the Genesis block mined (where did the Nonce an Nsilutioq
