### ISSUE TITLE
ipv6 protocol support

### ISSUE THREAD

**Issue by ddobreff** [z-classic/zclassic#45]
@joshuayabut
Adding this due to request.
Zcash daemon works with ipv6 peers but   zclassic seems to not support it.
`        "id" : 9,
        "addr" : "[2a02:c207:0:4197::1]:8233",
        "addrlocal" : "[2001:470:1f09:3b6:221:70ff:fe26:4422]:55960",
`

**Comment by aayanl** [comment]
I'm currently connected to an ipv6 peer, can you give more info on the problem?

**Comment by joshuayabut** [comment]
Closing due to staleness.
