### ISSUE TITLE
Connection is max 8 

### ISSUE THREAD

**Issue by alptolga** [z-classic/zclassic#47]
I made a clean install yesterday. Everything installed new (include os) Max connection is 8 . I added most of them to the config file manually. I think something is wrong. And also I just see the gui of the zclassic in terminal when I start it at the first time. I couldn't start with its gui again. How is it possible to start it again?

**Comment by aayanl** [comment]
what does getinfo show? There was an error where the gui capped at 8 but that should've been fixed

**Comment by alptolga** [comment]
it shows 8 connection.  I installed my first zclassic node 1 month ago and it connected tothe 19 peers. It's version is "version" : 1000350,

**Comment by alptolga** [comment]
A few minutes ago It showed 9 connection and a few second later  number of connection turned back to 8 again.

**Comment by joshuayabut** [comment]
Just to confirm.. you have set maxconnections= in the zclassic.conf file?
