### ISSUE TITLE
I can't make it.

### ISSUE THREAD

**Issue by ceozero** [z-classic/zclassic#48]
gmp-6.1.1.tar.bz2 && rm -rf /root/zclassic/depends/work/download/libgmp-6.1.1 ))
Fetching libgmp...
wget: 无法解析主机地址 “z.cash”
wget: 无法解析主机地址 “gmplib.org”
funcs.mk:238: recipe for target '/root/zclassic/depends/sources/download-stamps/.stamp_fetched-libgmp-gmp-6.1.1.tar.bz2.hash' failed
make: *** [/root/zclassic/depends/sources/download-stamps/.stamp_fetched-libgmp-gmp-6.1.1.tar.bz2.hash] Error 4
make: Leaving directory '/root/zclassic/depends'

**Comment by aayanl** [comment]
you're not supposed to use Make, run the build.sh script in zcutil
