### ISSUE TITLE
Add Seed Nodes

### ISSUE THREAD

**Issue by heyrhett** [z-classic/zclassic#5]
I would like to add more seed nodes to the startup code.

**Comment by kernelpanik23** [comment]
I will setup a full node asap.

**Comment by khoubaibc** [comment]
hi i have a new node 

please add this IP 197.12.8.45

live and synced

**Comment by GQM** [comment]
Just set this one up to help out ;)

dnsseed.zcl.cryptobanx.io
45.63.117.54

**Comment by joshuayabut** [comment]
Thanks all for putting nodes up! 

Next up we will need some testnet and .onion nodes.

**Comment by joshuayabut** [comment]
This work is staged in my ptolemy branch.

**Comment by kiahmed** [comment]
any active testnode out there?
