### ISSUE TITLE
Release v1.0.5a OSX damaged.

### ISSUE THREAD

**Issue by daxxog** [z-classic/zclassic#58]
I downloaded the latest MacOS release from: https://github.com/z-classic/zclassic/releases . I then ran the script and copied the application to my Applications folder.
Upon running the application I encountered: 
![screen shot 2017-02-07 at 12 17 30 pm](https://cloud.githubusercontent.com/assets/2145492/22705086/bece68a0-ed2f-11e6-989a-3d6a16b89783.png)

![screen shot 2017-02-07 at 12 22 13 pm](https://cloud.githubusercontent.com/assets/2145492/22705159/163917ca-ed30-11e6-9b1b-6e89d4f98775.png)

**Comment by joshuayabut** [comment]
Thanks for catching that... I'm about to upload a new graphical wallet either tonight or tomorrow for MacOS.

**Comment by nurazhar** [comment]
thanks waiting for the upload

**Comment by n1rvana** [comment]
Well, it's a month later.  Something happened?

**Comment by Pcmode** [comment]
Isn't this an issue with Gatekeeper on Sierra? Apple just changed a bunch of security features in the new release.

**Comment by Pcmode** [comment]
http://apple.stackexchange.com/questions/243687/allow-applications-downloaded-from-anywhere-in-macos-sierra

**Comment by mfgex** [comment]
still saying its damaged with latest version.  any updates?

**Comment by Stigermann** [comment]
I just downloaded version 1.0.6 for MacOS and it still says it is damaged and should be moved to the trash.

**Comment by Stigermann** [comment]
It is a security feature - see link 2 comments above.  You have to run sudo spctl --master-disable.

**Comment by joshuayabut** [comment]
Should be fixed now in latest release.
