### ISSUE TITLE
Node Version Update

### ISSUE THREAD

**Issue by dlehenky** [z-classic/zclassic#61]
I would like to ask you, when you merge the upstream zcash version updates, to *please* update the network node ID and various other version strings (zcashd --version, zcash-cli --version). It really creates a lot of confusion, for me, when the zclassic merge continues to report the previous version, other than a different build number (I think that's what it is: v1.0.5-de56a04). It's actually inaccurate when a peer does a "getpeerinfo", since my node continues to identify as v1.0.5, when it's really v1.0.6. I don't mean to be a nit; you all do a tremendous job keeping zclassic in sync with zcash, and we all appreciate you efforts very much. Thank you!

**Comment by joshuayabut** [comment]
Fixed in 1.0.8-1
