### ISSUE TITLE
Miner P2P Periodic Disconnect/Reconnect

### ISSUE THREAD

**Issue by dlehenky** [z-classic/zclassic#64]
I'm using the new equihash-solomining proxy. Periodically, the logs show the coin daemon (zclassic v1.0.6, sort of) disconnecting and reconnecting. The proxy logs don't give a timestamp, unfortunately, so I don't know the timing involved. There are no other errors reported. Ubuntu 14.04.03.

**Comment by aayanl** [comment]
issue with zcash
