### ISSUE TITLE
Zcash bug & security anoncement

### ISSUE THREAD

**Issue by a1binos** [z-classic/zclassic#68]
Hi!
https://z.cash/blog/security-announcement-2017-04-12.html

When it will be fixed in zclassic?

**Comment by dlehenky** [comment]
It is fixed in the latest release.

**Comment by joshuayabut** [comment]
Yup this has been merged into master. I'm working on building new binaries for the graphical wallets today and will update here once they are completed.

**Comment by a1binos** [comment]
Bittrex turned zcl wallets to go offline - I talk to support team, they waiting for developers to provide them new wallets. Check it.

**Comment by joshuayabut** [comment]
Closing this out as we submitted them the updated code
