### ISSUE TITLE
request:change filenames/references to zclassic from zcash 

### ISSUE THREAD

**Issue by mattyc3** [z-classic/zclassic#7]
...to enable those who might want to also mine zcash on the same system.
Inslalling zclassic can destroy existing zcash configs.

I'm not able to help mine and check out zclassic at the moment because of this.

Tried to hack here and there by using symlinks etc.. but it's too messy.

Just a thought and I'm surprised not addressed already.

**Comment by joshuayabut** [comment]
Updated data dir and config file #02cbc5dbbca84e3f651023624bcfd23ca188daa4. Still needs some more edits though to change the binary name and etc.

**Comment by joshuayabut** [comment]
Do we want to change the zcashd and zcash-cli to zclassic??

**Comment by aayanl** [comment]
I say we do but have it generate both for a few releases then only generate zclassic.

**Comment by Vash63** [comment]
Any update on this? I have an existing zcash wallet and would like to have both wallets for a while without needing a separate user or similar hack.

**Comment by ch4ot1c** [comment]
Please see https://github.com/z-classic/zclassic/issues/152 too
