### ISSUE TITLE
"Activating best chain" can't access wallet.

### ISSUE THREAD

**Issue by XYZclassic** [z-classic/zclassic#73]
When opening wallet, I get the spinning box animation and the message "activating best chain".  The message does not go away and I cannot access the wallet.

I am using v1.0.6 with the eleos windows client.

Machine specs:
- Windows 10
- CPU: i5 4690k
- RAM: 8GB
- Disk size: 500GB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
I can't find the debug log in eleos.

### Do you have a back up of `~/.zcash` directory and/or take a VM snapshot?
Could you please tell me what to redact?  I'm not a dev so I don't know where info like my seed/coins are.

Thank you in advance for your help!

**Comment by XYZclassic** [comment]
Okay so I resolved this by running 'zcashd -reindex'.  This took a LONG time to get to the current block height.  ~ 40 minutes with 55mbps down.  Can you please explain how to back up the coins?  I'm a new user and want to support ZCL but so far my experience is shaky.  Perhaps putting this in the README for other new users would be a good idea.  Thanks so much!

**Comment by joshuayabut** [comment]
For windows the wallet.dat file is stored in %APPDATA%/Zclassic or %APPDATA%/Zcash.

Once I get some time I'll work on creating the documentation :0)

**Comment by XYZclassic** [comment]
Awesome!  I completely missed that folder because I assumed there was only an Eleos folder in %appdata%.  So if I backup wallet.dat, what is the purpose of the dump file produced by `zcashd -exportdir=PATH -daemon` `zcash-cli z_exportwallet MyWallet`?  Also, I'm guessing just overwriting a wallet.dat file restores the wallet.  That seems way easier that using `z_importwallet`.  I appreciate the help

**Comment by aayanl** [comment]
Closing due to staleness
