### ISSUE TITLE
Cannot send cash with .xxx must include leading 0.xxx

### ISSUE THREAD

**Issue by fittsy** [z-classic/zclassic#80]
The .0.1.0 windows wallet has a bug.

You cannot send a transaction of a small amount of ZCL under 1 unless you use the leading zero.
For example. I was just trying to send .25 zcl. It wouldn't work. I had to type 0.25 zcl to get it to work.

The code should definitely be more intelligent as it took me awhile to figure out why I wasn't able to send that transaction. My wallet had plenty of funds.  Less technical users may get confused and give up or open support requests rather than trying the leading 0.

**Comment by aayanl** [comment]
you need a leading 0 for it to be valid json

**Comment by fittsy** [comment]
To amend the code to create valid JSON by adding a 0 to transactions that start with . would be more user friendly.
