### ISSUE TITLE
gflock command not found during the fetch-params

### ISSUE THREAD

**Issue by Huge** [z-classic/zclassic#82]
### 
Following [the steps for installing on Linux](https://github.com/z-classic/zclassic#linux) i got the error described bellow. Should I be worried? What's the cause?

### Steps to reproduce:
1. $ `./zcutil/fetch-params.sh`
2. See it put out: 
```
./zcutil/fetch-params.sh: line 62: gflock: command not found
Only one instance of fetch-params.sh can be run at a time.
Zcash - fetch-params.sh
This script will fetch the Zcash zkSNARK parameters and verify their
integrity with sha256sum.
If (...)
```

### The version of Zcash used:
$ `./src/zcashd --version`:
> `Zcash Daemon version v1.0.8-1-33b3b6d`

### Machine specs:
- OS Ubuntu 14.04.5
- CPU: 4 cores Intel
- RAM: 22 GB
- Linux kernel version (uname -a): 3.13.0-119-generic
- Compiler version (gcc --version): 4.8.4

My first installation so I might have gone wrong somewhere.?.

**Comment by aayanl** [comment]
Can you make this change to that script? https://github.com/z-classic/zclassic/pull/83/files

**Comment by Huge** [comment]
Removed that letter and no error shown now. It just wrote it "will exit now and do nothing else" and so it did.
