### ISSUE TITLE
Stuck at "Mining is paused while waiting for connections."

### ISSUE THREAD

**Issue by Huge** [z-classic/zclassic#84]
Trying to get my node running I've added the nodes as suggested in https://github.com/z-classic/zclassic/issues/17#issuecomment-260202952 and/or in the https://github.com/z-classic/zclassic/wiki/1.0-User-Guide#running-zcash . I get stuck at 
````
Mining is paused while waiting for connections.
````
I am most likely behind NAT and did not _open/map TCP Port 8133_ as suggested. Is that causing the lag? Is this to be done on gateway to the intranet/NAT?? I don't have access to that, I think...

**Comment by Huge** [comment]
https://github.com/zcash/zcash/issues/1416#issuecomment-251744858 is pointing to the generic work-around via Tor?.?

**Comment by aayanl** [comment]
You need to get connections before mining
