### ISSUE TITLE
zclassic.org: Add a favicon

### ISSUE THREAD

**Issue by davidhedlund** [z-classic/zclassic#87]
There is no favicon for zclassic.org, can you please add it?

I need to upload the icon to bitcoin.it so I can add it to their [Comparison of cryptocurrencies](https://en.bitcoin.it/wiki/Comparison_of_cryptocurrencies) article. Please check it out!

**Comment by joshuayabut** [comment]
Looks to be added :)

**Comment by davidhedlund** [comment]
@joshuayabut Yes, but it would look so much more professional if you represented your own website with it as well.
