### ISSUE TITLE
black hole of transactions

### ISSUE THREAD

**Issue by fineartcommodities** [z-classic/zclassic#99]
Before the fork I had 160 ZCL on a wallet with this addresses:
t1h1jS85o1JfU3qRiTih3fhsgTVB1Cd9XYo
t1RenUEheyjFNxd61egNbTdiF7UgaDjqfTa

after the fork I was (and I'm able) to send and recive ZCL:

06/08/2017	ZCL	10.00000000
To Address: t1Qi2ZD6a8ah6uQHhQtZ1C18U8jaG53BfsR
TxId: 4fc324140a7519bf9b618e2c95309a2faf5e39d6ea985a914dc6e64dd4bcb002

on 06/08/2017 in my own ZCL wallet I had 150 prefork ZCL

Look at that now:

IN,Yes (925),150.00,4-ago-2017 22.13.04,t1h1jS85o1JfU3qRiTih3fhsgTVB1Cd9XYo,4b03c02c43fa3f2fdc402a070045b54881608fa387a1a4b9b60e4335b6ffaec6
?T (Public),? 

I recive MY 150 ZCL I already had.

Transactions between 30-apr-2017 and 4-ago-2017 are not listed in Zclassic Windows Wallet 0.1.0
See:

05/02/2017	ZCL	99.99800000	Completed
Address: t1RenUEheyjFNxd61egNbTdiF7UgaDjqfTa
TxId: 64835ab860c0cbcdc2e027dd596df6a562fbe680d860df1cef033d51b3cc2efe

05/02/2017	ZCL	100.29094213	Completed
Address: t1RenUEheyjFNxd61egNbTdiF7UgaDjqfTa
TxId: fa934c5278da996a0af0de7c4b0b2bb0f3af6545e79584b78db89e13ba4c2a79

and

05/17/2017	ZCL	160.00000000
Address: t1Qi2ZD6a8ah6uQHhQtZ1C18U8jaG53BfsR
TxId: f161e7419afca8626d83ab95077a81fa2b9a8261285c4dcb98a08ce4c22268dd

This 3 transaction rouled but missing in my transaction history:

Type,I/O,Conf.,Amount,Date,Destination Address,Tx
☆T (Public),⇦ OUT,Yes (67),2.00,6-ago-2017 10.29.30,t1Qi2ZD6a8ah6uQHhQtZ1C18U8jaG53BfsR,4904f1e233e36a640f87d867b9f43d6e61eb9cc4ae739ec16c0024ceba345bf3
☆T (Public),⇦ OUT,Yes (68),1.00,6-ago-2017 10.28.19,t1Qi2ZD6a8ah6uQHhQtZ1C18U8jaG53BfsR,f1ee8b0789db3895db5a9f3b32c7b24a4bfd00abb2eef4419c50d60bb2bf8421
☆T (Public),⇨ IN,Yes (925),150.00,4-ago-2017 22.13.04,t1h1jS85o1JfU3qRiTih3fhsgTVB1Cd9XYo,4b03c02c43fa3f2fdc402a070045b54881608fa387a1a4b9b60e4335b6ffaec6
☆T (Public),⇦ OUT,Yes (55397),119.33343504,30-apr-2017 22.19.11,t1RenUEheyjFNxd61egNbTdiF7UgaDjqfTa,dea917b2ab62ad7e2ca835a54769693e2de2847708709732b7855daea40c0d4d
☆T (Public),⇦ OUT,Yes (55397),29.90,30-apr-2017 22.19.11,t1Qi2ZD6a8ah6uQHhQtZ1C18U8jaG53BfsR,dea917b2ab62ad7e2ca835a54769693e2de2847708709732b7855daea40c0d4d
☆T (Public),⇦ OUT,Yes (55397),0.9959,30-apr-2017 22.19.11,t1RenUEheyjFNxd61egNbTdiF7UgaDjqfTa,7625023d5c2285d312d72c3b8a5fcfe065e2a9ba975f112a614698c95b8a4f27
☆T (Public),⇦ OUT,Yes (55397),0.10,30-apr-2017 22.19.11,t1Qi2ZD6a8ah6uQHhQtZ1C18U8jaG53BfsR,7625023d5c2285d312d72c3b8a5fcfe065e2a9ba975f112a614698c95b8a4f27
☆T (Public),⇨ IN,Yes (55943),149.23353504,29-apr-2017 23.04.57,t1h1jS85o1JfU3qRiTih3fhsgTVB1Cd9XYo,f28e7e553aa5f228a889656eb5e637f39d0b809558458e35ebf1ae7849956496
☆T (Public),⇨ IN,Yes (55955),0.998,29-apr-2017 22.51.15,t1h1jS85o1JfU3qRiTih3fhsgTVB1Cd9XYo,54e85c4faf8c8551ef31c8d408a08c386183d238a75f089b7fc93fd84e98981a
☆T (Public),⇨ IN,Yes (55976),0.098,29-apr-2017 21.38.38,t1h1jS85o1JfU3qRiTih3fhsgTVB1Cd9XYo,53c825008b37528c49c8e419c10ee9629068c3d726286dc5d2635ceae8cc8225

Now.
I think this is the reason why I don't see any balance in ZEN eleos 0.0.9. 
In fact when I import zcl wallet.dat into eleos I just can see transactions ending on 30-apr-2017!
And obviously my ZEN balance is zero.

How do I do to have my ZEN now?

**Comment by joshuayabut** [comment]
This is not a ZCL issue.
